# Generated by Django 3.2.8 on 2021-10-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icodeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_pub',
        ),
    ]
