# Generated by Django 3.2.8 on 2021-11-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icodeapp', '0007_auto_20211108_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
